version: "3.9"
services:
  wcs:
    tty: true
    ports:
      - "80:80"
    image: docker.io/pdok/mapserver:7.6.4-patch5-buster-lighttpd-nl
    volumes:
      - ./data:/srv/data
      - ./service.map:/srv/service.map
    environment:
      MS_MAPFILE: "/srv/service.map"
      CPL_VSIL_CURL_CHUNK_SIZE: "1048576"
      GDAL_INGESTED_BYTES_AT_OPEN: "32768"
      CPL_VSIL_CURL_CACHE_SIZE: "1887436800"
      GDAL_CACHEMAX: "1800"
    command: >
      /bin/bash -c "lighttpd -D -f /lighttpd.conf"
  do-requests:
    tty: true
    depends_on:
      - wcs
    image: pdok/multitool:latest
    volumes:
      - ./do-getcov-req.sh:/scripts/do-getcov-req.sh
      - ./split-multipart.sh:/scripts/split-multipart.sh
      - ./output-data:/srv/output-data:rw
    command: >
      /bin/bash -c "/scripts/do-getcov-req.sh http://wcs"
