version: "3.9"
services:
  wcs:
    tty: true
    ports:
      - "80:80"
    image: docker.io/pdok/mapserver:7.6.4-patch5-buster-lighttpd-nl
    volumes:
      - ./data:/srv/data
      - ./service.map:/etc/service.map
    environment:
      MS_MAPFILE: "/etc/service.map"
    command: >
      /bin/bash -c "lighttpd -D -f /lighttpd.conf"
  do-requests:
    tty: true
    depends_on:
      - wcs
    image: pdok/multitool:latest
    volumes:
      - ./do-getcov-req.sh:/scripts/do-getcov-req.sh
      - ./split-multipart.sh:/scripts/split-multipart.sh
      - ./output-data:/srv/output-data:rw
      - ./data:/srv/data
    command: >
      /bin/bash -c "/scripts/do-getcov-req.sh /srv/data docker-compose http://wcs"
